name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below to help us resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Execute command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happens...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Relevant logs from `docker compose logs <service>` or error messages.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      render: shell
      placeholder: Paste logs here...
    validations:
      required: false

  - type: input
    id: service
    attributes:
      label: Affected Service(s)
      description: Which service(s) are affected by this bug?
      placeholder: "e.g., traefik, nextcloud, authelia"
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Deployment Environment
      description: Where are you running Omakase?
      options:
        - Proxmox LXC
        - Bare Metal
        - Virtual Machine
        - Docker on NAS
        - Cloud VPS
        - Other
    validations:
      required: true

  - type: input
    id: docker-version
    attributes:
      label: Docker Version
      description: Output of `docker --version`
      placeholder: "e.g., Docker version 24.0.7, build afdd53b"
    validations:
      required: true

  - type: input
    id: compose-version
    attributes:
      label: Docker Compose Version
      description: Output of `docker compose version`
      placeholder: "e.g., Docker Compose version v2.23.3"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your host OS and version
      placeholder: "e.g., Ubuntu 22.04 LTS"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (screenshots, config snippets, etc.)
      placeholder: Add any other context here...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked existing issues to avoid duplicates
          required: true
        - label: I have included all relevant information above
          required: true
        - label: I have removed any sensitive information from logs
          required: true
